### ISSUE TITLE
Duration prop on the <Toaster /> is not recognized by typescript

### ISSUE THREAD

**Issue by Hugos68** [wobsoriano/svelte-sonner#50]
### Describe the bug

Title says it all, type definition isn't present for duration prop

### Reproduction

1. Create typescript sveltekit project
2. Install svelte-sonner
3. Add <Toaster /> anywhere
4. Add duration prop to <Toaster />
5. Observer the type error

### System Info

```bash
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 20.34 GB / 31.93 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^2.3.2 => 2.3.2
    svelte: ^4.2.8 => 4.2.8
    svelte-sonner: ^0.3.11 => 0.3.11
```

### Severity

annoyance

**Comment by enyo** [comment]
That's because it seems to have been removed:

https://github.com/wobsoriano/svelte-sonner/commit/93f282c6040b499564ef6f4d92a2834a3a09b552#diff-0fe79c63b875a6f66b16c4c089951eeb191d9a9f657fb008c4c5b3eb918e264aL53

I just ran into the same problem and would also like to know the reasoning behind this.
